//
// Clouds.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Clouds: Codable {

    /** Cloudiness, % */
    public var all: Int?

    public init(all: Int?) {
        self.all = all
    }


}

