//
// Coord.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Coord: Codable {

    /** City geo location, longitude */
    public var lon: Double?
    /** City geo location, latitude */
    public var lat: Double?

    public init(lon: Double?, lat: Double?) {
        self.lon = lon
        self.lat = lat
    }


}

