//
// Main.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Main: Codable {

    /** Temperature. Unit Default: Kelvin, Metric: Celsius, Imperial: Fahrenheit. */
    public var temp: Double?
    /** Atmospheric pressure (on the sea level, if there is no sea_level or grnd_level data), hPa */
    public var pressure: Int?
    /** Humidity, % */
    public var humidity: Int?
    /** Minimum temperature at the moment. This is deviation from current temp that is possible for large cities and megalopolises geographically expanded (use these parameter optionally). Unit Default: Kelvin, Metric: Celsius, Imperial: Fahrenheit. */
    public var tempMin: Double?
    /** Maximum temperature at the moment. This is deviation from current temp that is possible for large cities and megalopolises geographically expanded (use these parameter optionally). Unit Default: Kelvin, Metric: Celsius, Imperial: Fahrenheit. */
    public var tempMax: Double?
    /** Atmospheric pressure on the sea level, hPa */
    public var seaLevel: Double?
    /** Atmospheric pressure on the ground level, hPa */
    public var grndLevel: Double?

    public init(temp: Double?, pressure: Int?, humidity: Int?, tempMin: Double?, tempMax: Double?, seaLevel: Double?, grndLevel: Double?) {
        self.temp = temp
        self.pressure = pressure
        self.humidity = humidity
        self.tempMin = tempMin
        self.tempMax = tempMax
        self.seaLevel = seaLevel
        self.grndLevel = grndLevel
    }

    public enum CodingKeys: String, CodingKey { 
        case temp
        case pressure
        case humidity
        case tempMin = "temp_min"
        case tempMax = "temp_max"
        case seaLevel = "sea_level"
        case grndLevel = "grnd_level"
    }


}

