//
// Rain.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Rain: Codable {

    /** Rain volume for the last 3 hours */
    public var _3h: Int?

    public init(_3h: Int?) {
        self._3h = _3h
    }

    public enum CodingKeys: String, CodingKey { 
        case _3h = "3h"
    }


}

