//
// Snow.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Snow: Codable {

    /** Snow volume for the last 3 hours */
    public var _3h: Double?

    public init(_3h: Double?) {
        self._3h = _3h
    }

    public enum CodingKeys: String, CodingKey { 
        case _3h = "3h"
    }


}

