//
// Sys.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Sys: Codable {

    /** Internal parameter */
    public var type: Int?
    /** Internal parameter */
    public var id: Int?
    /** Internal parameter */
    public var message: Double?
    /** Country code (GB, JP etc.) */
    public var country: String?
    /** Sunrise time, unix, UTC */
    public var sunrise: Int?
    /** Sunset time, unix, UTC */
    public var sunset: Int?

    public init(type: Int?, id: Int?, message: Double?, country: String?, sunrise: Int?, sunset: Int?) {
        self.type = type
        self.id = id
        self.message = message
        self.country = country
        self.sunrise = sunrise
        self.sunset = sunset
    }


}

