//
// Model200.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct WeatherModel200: Codable {

    public var coord: Coord?
    /** (more info Weather condition codes) */
    public var weather: [Weather]?
    /** Internal parameter */
    public var base: String?
    public var main: Main?
    /** Visibility, meter */
    public var visibility: Int?
    public var wind: Wind?
    public var clouds: Clouds?
    public var rain: Rain?
    public var snow: Snow?
    /** Time of data calculation, unix, UTC */
    public var dt: Int?
    public var sys: Sys?
    /** City ID */
    public var id: Int?
    public var name: String?
    /** Internal parameter */
    public var cod: String?

    public init(coord: Coord?, weather: [Weather]?, base: String?, main: Main?, visibility: Int?, wind: Wind?, clouds: Clouds?, rain: Rain?, snow: Snow?, dt: Int?, sys: Sys?, id: Int?, name: String?, cod: String?) {
        self.coord = coord
        self.weather = weather
        self.base = base
        self.main = main
        self.visibility = visibility
        self.wind = wind
        self.clouds = clouds
        self.rain = rain
        self.snow = snow
        self.dt = dt
        self.sys = sys
        self.id = id
        self.name = name
        self.cod = cod
    }


}

