//
// Weather.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Weather: Codable {

    /** Weather condition id */
    public var id: Int?
    /** Group of weather parameters (Rain, Snow, Extreme etc.) */
    public var main: String?
    /** Weather condition within the group */
    public var description: String?
    /** Weather icon id */
    public var icon: String?

    public init(id: Int?, main: String?, description: String?, icon: String?) {
        self.id = id
        self.main = main
        self.description = description
        self.icon = icon
    }


}

